version: '3.3'
services:

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

  db:
    container_name: foodgram-db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web Console
    env_file:
      - .env.s3
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"


volumes:
  postgres_data: {}
  minio_data: {}
